# Generated by Django 4.0 on 2022-03-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0002_db_bills_inv_amount_1_db_bills_inv_amount_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_bills',
            name='qtn_amt1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_amt10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_amt2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_amt3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_amt4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_amt5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_amt6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_amt7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_amt8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_amt9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_description1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_description10',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_description2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_description3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_description4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_description5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_description6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_description7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_description8',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_description9',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_qty1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_qty10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_qty2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_qty3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_qty4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_qty5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_qty6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_qty7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_qty8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_qty9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_rate1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_rate10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_rate2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_rate3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_rate4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_rate5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_rate6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_rate7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_rate8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_rate9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_total_amount',
            field=models.FloatField(null=True),
        ),
    ]
