# Generated by Django 4.0 on 2022-03-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0003_db_bills_qtn_amt1_db_bills_qtn_amt10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_bills',
            name='qtn_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
