# Generated by Django 4.0 on 2022-03-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0004_db_bills_qtn_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_bills',
            name='qtn_amt1',
            field=models.FloatField(default=0, null=True),
        ),
    ]
