# Generated by Django 4.0 on 2022-03-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0005_alter_db_bills_qtn_amt1'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_bills',
            name='del_amount1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_amount2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_amount3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_amount4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_amount5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_chessis1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_chessis2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_chessis3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_chessis4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_chessis5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_descrtiption1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_descrtiption2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_descrtiption3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_descrtiption4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_descrtiption5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_engine1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_engine2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_engine3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_engine4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_engine5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_qty1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_qty2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_qty3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_qty4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_qty5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='del_total_amount',
            field=models.FloatField(null=True),
        ),
    ]
