# Generated by Django 4.0 on 2022-03-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0008_db_bills_mrm_amount_db_bills_mrm_amt_in_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_bills',
            name='qtn_no',
            field=models.IntegerField(null=True),
        ),
    ]
