# Generated by Django 4.0 on 2022-03-07 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0009_db_bills_qtn_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Margin_Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_mobile', models.CharField(max_length=50)),
                ('cust_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bills.db_bills', verbose_name='')),
            ],
        ),
    ]
