# Generated by Django 4.0 on 2022-03-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0010_db_margin_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_bills',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
