# Generated by Django 4.0 on 2022-03-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0011_alter_db_bills_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_bills',
            old_name='mrm_amount',
            new_name='mrm_amount1',
        ),
        migrations.RenameField(
            model_name='db_bills',
            old_name='mrm_date',
            new_name='mrm_amount2',
        ),
        migrations.RenameField(
            model_name='db_bills',
            old_name='mrm_hyp',
            new_name='mrm_amount3',
        ),
        migrations.RenameField(
            model_name='db_bills',
            old_name='mrm_payment_mode',
            new_name='mrm_amount4',
        ),
        migrations.RenameField(
            model_name='db_bills',
            old_name='mrm_region',
            new_name='mrm_amount5',
        ),
        migrations.RenameField(
            model_name='db_bills',
            old_name='mrm_amt_in_word',
            new_name='mrm_amt_in_word1',
        ),
        migrations.RenameField(
            model_name='db_bills',
            old_name='mrm_no',
            new_name='mrm_no1',
        ),
        migrations.RenameField(
            model_name='db_bills',
            old_name='mrm_remark',
            new_name='mrm_remark1',
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_amt_in_word2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_amt_in_word3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_amt_in_word4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_amt_in_word5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_date1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_date2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_date3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_date4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_date5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_hyp1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_hyp2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_hyp3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_hyp4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_hyp5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_no2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_no3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_no4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_no5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_payment_mode1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_payment_mode2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_payment_mode3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_payment_mode4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_payment_mode5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_region1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_region2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_region3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_region4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_region5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_remark2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_remark3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_remark4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_remark5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='DB_Margin_Money',
        ),
    ]
