# Generated by Django 4.0 on 2022-03-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0012_rename_mrm_amount_db_bills_mrm_amount1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_bills',
            old_name='mrm_no1',
            new_name='mrm_no',
        ),
        migrations.RemoveField(
            model_name='db_bills',
            name='mrm_no2',
        ),
        migrations.RemoveField(
            model_name='db_bills',
            name='mrm_no3',
        ),
        migrations.RemoveField(
            model_name='db_bills',
            name='mrm_no4',
        ),
        migrations.RemoveField(
            model_name='db_bills',
            name='mrm_no5',
        ),
    ]
