# Generated by Django 4.0 on 2022-03-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0014_db_bills_mrm_amount10_db_bills_mrm_amount11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_bills',
            name='mrm_region10',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_region11',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_region12',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_region13',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_region14',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_region15',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_region6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_region7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_region8',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='mrm_region9',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
