# Generated by Django 4.0.3 on 2022-03-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0015_db_bills_mrm_region10_db_bills_mrm_region11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_bills',
            name='branch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
