# Generated by Django 4.0.3 on 2022-03-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0016_db_bills_branch_alter_db_bills_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_bills',
            name='cust_pin_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='branch',
            field=models.CharField(choices=[('Vaijapur', 'Vaijapur'), ('Gangapur', 'Gangapur')], max_length=50, null=True),
        ),
    ]
