# Generated by Django 4.0.3 on 2022-03-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0018_db_bills_mrm_total_amt_alter_db_bills_cust_dist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_bills',
            name='del_amt_in_word',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='inv_amt_in_word',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_bills',
            name='qtn_amt_in_word',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
