# Generated by Django 4.0.3 on 2022-03-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0019_db_bills_del_amt_in_word_db_bills_inv_amt_in_word_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_bills',
            name='del_engine1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='del_engine2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='del_engine3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='del_engine4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='del_engine5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amount1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amount10',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amount11',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amount12',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amount13',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amount14',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amount15',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amount2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amount3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amount4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amount5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amount6',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amount7',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amount8',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amount9',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amt_in_word1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amt_in_word10',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amt_in_word11',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amt_in_word12',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amt_in_word13',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amt_in_word14',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amt_in_word15',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amt_in_word2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amt_in_word3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amt_in_word4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amt_in_word5',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amt_in_word6',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amt_in_word7',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amt_in_word8',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_amt_in_word9',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_date1',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_date10',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_date11',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_date12',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_date13',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_date14',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_date15',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_date2',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_date3',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_date4',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_date5',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_date6',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_date7',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_date8',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_date9',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_bills',
            name='mrm_region1',
            field=models.CharField(choices=[('Adjustable Locking Bolt (Front Weight)', 'Adjustable Locking Bolt (Front Weight)'), ('Alternator 7.5 KVA', 'Alternator 7.5 KVA'), ('Bumper', 'Bumper'), ('Bumper 4WD ( C-Channel Type)', 'Bumper 4WD ( C-Channel Type)'), ('Bumper 4WD Heavy (40 kg)', 'Bumper 4WD Heavy (40 kg)'), ('Bumper 4WD Heavy (60 kg)', 'Bumper 4WD Heavy (60 kg)'), ('CAPTAIN 280-DI 4WD OIB', 'CAPTAIN 280-DI 4WD OIB'), ('CAPTAIN 283-DI 4WD OIB', 'CAPTAIN 283-DI 4WD OIB'), ('CAPTAIN  200 DI 4WD - PS', 'CAPTAIN  200 DI 4WD - PS'), ('CAPTAIN 200 DI 4WD-OIB', 'CAPTAIN 200 DI 4WD-OIB'), ('CAPTAIN 200 DI 4WD- NT', 'CAPTAIN 200 DI 4WD- NT'), ('CAPTAIN 200 DI 4WD- NT-PS', 'CAPTAIN 200 DI 4WD- NT-PS'), ('CAPTAIN 200 DI 4WD-HO-PS', 'CAPTAIN 200 DI 4WD-HO-PS'), ('CAPTAIN 200DI -HS', 'CAPTAIN 200DI -HS'), ('CAPTAIN 200DI -NT', 'CAPTAIN 200DI -NT'), ('CAPTAIN 250 4WD -PS-FT- 6.00 X 12 ,RT- 8.3x20', 'CAPTAIN 250 4WD -PS-FT- 6.00 X 12 ,RT- 8.3x20'), ('CAPTAIN 250 DI 4WD - FT- 6.00 X 12 ,RT- 8.3x20- OIB-HO', 'CAPTAIN 250 DI 4WD - FT- 6.00 X 12 ,RT- 8.3x20- OIB-HO'), ('CAPTAIN 250 DI 4WD -NT-OIB', 'CAPTAIN 250 DI 4WD -NT-OIB'), ('CAPTAIN 250 DI 4WD -NT-PS-OIB', 'CAPTAIN 250 DI 4WD -NT-PS-OIB'), ('CAPTAIN 250 DI 4WD -PS- FT- 6.00 X 12 ,RT- 8.3x20- OIB-HO', 'CAPTAIN 250 DI 4WD -PS- FT- 6.00 X 12 ,RT- 8.3x20- OIB-HO'), ('CAPTAIN 250 DI 4WD-OIB', 'CAPTAIN 250 DI 4WD-OIB'), ('CAPTAIN 250 DI 4WD-OIB-FT- 6.00 X 12 ,RT- 8.3x20-', 'CAPTAIN 250 DI 4WD-OIB-FT- 6.00 X 12 ,RT- 8.3x20-'), ('CAPTAIN 250 DI 4WD-PS-OIB', 'CAPTAIN 250 DI 4WD-PS-OIB'), ('CAPTAIN 250 DI FT- 5.25x14 ,RT 8.3X20-PS-OIB-LD', 'CAPTAIN 250 DI FT- 5.25x14 ,RT 8.3X20-PS-OIB-LD'), ('CAPTAIN 250 DI FT-5.00X15 ,9.5X24-OIB', 'CAPTAIN 250 DI FT-5.00X15 ,9.5X24-OIB'), ('CAPTAIN 250 DI FT-5.00X15 ,9.5X24-PS-OIB', 'CAPTAIN 250 DI FT-5.00X15 ,9.5X24-PS-OIB'), ('CAPTAIN 250 DI FT-5.25x14 ,RT 8.3X20  -OIB', 'CAPTAIN 250 DI FT-5.25x14 ,RT 8.3X20  -OIB'), ('CAPTAIN 250 DI FT-5.25x14 ,RT 8.3X20  PS-OIB', 'CAPTAIN 250 DI FT-5.25x14 ,RT 8.3X20  PS-OIB'), ('CAPTAIN 250 DI-HS-PS-O', 'CAPTAIN 250 DI-HS-PS-O'), ('CAPTAIN 250 DI-OIB', 'CAPTAIN 250 DI-OIB'), ('CAPTAIN 280-DI 4WD-NT-PS-OB-BI', 'CAPTAIN 280-DI 4WD-NT-PS-OB-BI'), ('CAPTAIN 280-DI 4WD-OIB-FT- 6.00 X 12 ,RT- 8.3x20-', 'CAPTAIN 280-DI 4WD-OIB-FT- 6.00 X 12 ,RT- 8.3x20-'), ('CAPTAIN 280-DI 4WD-OIB-FT- 6.00 X 12 ,RT- 8.3x20-HO', 'CAPTAIN 280-DI 4WD-OIB-FT- 6.00 X 12 ,RT- 8.3x20-HO'), ('CAPTAIN 280-DI 4WD-PS-OIB-FT- 6.00 X 12 ,RT- 8.3x20-', 'CAPTAIN 280-DI 4WD-PS-OIB-FT- 6.00 X 12 ,RT- 8.3x20-'), ('CAPTAIN 280-DI 4WD-PS-OIB', 'CAPTAIN 280-DI 4WD-PS-OIB'), ('CAPTAIN 280 DX- FT.5.00X15 RT-9.5X24-OIB', 'CAPTAIN 280 DX- FT.5.00X15 RT-9.5X24-OIB'), ('CAPTAIN 280 DX- FT.5.00X15 RT-9.5X24-PS-OIB', 'CAPTAIN 280 DX- FT.5.00X15 RT-9.5X24-PS-OIB'), ('CAPTAIN 280DI -PS-OB-LD', 'CAPTAIN 280DI -PS-OB-LD'), ('Centrifugal Pump (3”x 2.5”)', 'Centrifugal Pump (3”x 2.5”)'), ('CENTRIFUGAL PUMP (4”X4”)', 'CENTRIFUGAL PUMP (4”X4”)'), ('CHAFF CUTTER - 24"', 'CHAFF CUTTER - 24"'), ('Cultivator - 3 Chisel', 'Cultivator - 3 Chisel'), ('CULTIVATOR - 7 SPRING TYN', 'CULTIVATOR - 7 SPRING TYN'), ('Cultivator -5 Duck foot', 'Cultivator -5 Duck foot'), ('Cultivator -5 Duck foot (Set)', 'Cultivator -5 Duck foot (Set)'), ('Cultivator -5 Tine', 'Cultivator -5 Tine'), ('Cultivator -5 Tine (Set)', 'Cultivator -5 Tine (Set)'), ('CULTIVATOR 5-SPRING TYNE', 'CULTIVATOR 5-SPRING TYNE'), ('Cultivator -7 Duck foot', 'Cultivator -7 Duck foot'), ('Cultivator 7 Tine', 'Cultivator 7 Tine'), ('Cultivator Blade type (2-Row', 'Cultivator Blade type (2-Row'), ('Cultivator Bracket Bullock Drawn', 'Cultivator Bracket Bullock Drawn'), ('Cultivator Height Attachmen', 'Cultivator Height Attachmen'), ('Disc Harrow (14 Disc) 18"', 'Disc Harrow (14 Disc) 18"'), ('Disc Harrow (16 Disc) 18"', 'Disc Harrow (16 Disc) 18"'), ('DISC PLOUGH - 22" (2-Ballota DISC)', 'DISC PLOUGH - 22" (2-Ballota DISC)'), ('DISC PLOUGH REVERSIBLE - 22" (2- Ballota DISC', 'DISC PLOUGH REVERSIBLE - 22" (2- Ballota DISC'), ('Frame, Front Weight', 'Frame, Front Weight'), ('Frame,Canopy Mounting', 'Frame,Canopy Mounting'), ('Front Weight , (20KG)', 'Front Weight , (20KG)'), ('Furrow Attachment', 'Furrow Attachment'), ('Half Cage wheel - LH & RH', 'Half Cage wheel - LH & RH'), ('Height Attachement -60"(4WD)', 'Height Attachement -60"(4WD)'), ('Height Attachment - 48" (2WD)', 'Height Attachment - 48" (2WD)'), ('HEIGHT ATTACHMENT – 48” (2WD) (2 FT. G.C.)', 'HEIGHT ATTACHMENT – 48” (2WD) (2 FT. G.C.)'), ('HEIGHT ATTACHMENT – 48” (4WD) (2 FT. G.C.)', 'HEIGHT ATTACHMENT – 48” (4WD) (2 FT. G.C.)'), ('Height Attachment - 48”(4WD)', 'Height Attachment - 48”(4WD)'), ('Height attachment - 60" (2WD)', 'Height attachment - 60" (2WD)'), ('Hood (Rajwadi)', 'Hood (Rajwadi)'), ('Land Leveler', 'Land Leveler'), ('MOULD BOARD PLOUGH - 2 FARROW (HEAVY)', 'MOULD BOARD PLOUGH - 2 FARROW (HEAVY)'), ('Mould Board Plough 2 Farrow', 'Mould Board Plough 2 Farrow'), ('Mould Board Plough 3 Farrow', 'Mould Board Plough 3 Farrow'), ('Mould Board Plough Reversible', 'Mould Board Plough Reversible'), ('Mould Board Plough Reversible (Heavy)', 'Mould Board Plough Reversible (Heavy)'), ('Post Hole Digger 9 inch', 'Post Hole Digger 9 inch'), ('POTATO DIGGER', 'POTATO DIGGER'), ('POTATO PLANTER', 'POTATO PLANTER'), ('Puddler', 'Puddler'), ('Ridger (1 Row)', 'Ridger (1 Row)'), ('Ridger (2 Row)', 'Ridger (2 Row)'), ('Rod, Locking (Front Weight)', 'Rod, Locking (Front Weight)'), ('ROPS', 'ROPS'), ('Rotary Tiller (RF) 0.7M', 'Rotary Tiller (RF) 0.7M'), ('Rotary Tiller 0.8m (L Type )', 'Rotary Tiller 0.8m (L Type )'), ('Rotary Tiller 1.2m (L Type )', 'Rotary Tiller 1.2m (L Type )'), ('Rotary Tiller 1m. (L Type )', 'Rotary Tiller 1m. (L Type )'), ('Roto Seed Drill (Attachment)', 'Roto Seed Drill (Attachment)'), ('Seed cum Fertilizer Drill 5×10', 'Seed cum Fertilizer Drill 5×10'), ('Seed cum Fertilizer Drill 5×10 (Without cultivato', 'Seed cum Fertilizer Drill 5×10 (Without cultivato'), ('Seed cum Fertilizer Drill 7×14', 'Seed cum Fertilizer Drill 7×14'), ('Seed cum Fertilizer Drill 7×14 (Without cultivato', 'Seed cum Fertilizer Drill 7×14 (Without cultivato'), ('Sprayer Pump (Horticulture)', 'Sprayer Pump (Horticulture)'), ('SPRAYER PUMP 8 NOZZLE (VERTICAL- 500 Ltr.)', 'SPRAYER PUMP 8 NOZZLE (VERTICAL- 500 Ltr.)'), ('Sprayer Pump 8 nozzle (Vertical)', 'Sprayer Pump 8 nozzle (Vertical)'), ('Sprayer Pump 8 Nozzle (Vertical-300 Ltr.)', 'Sprayer Pump 8 Nozzle (Vertical-300 Ltr.)'), ('Sprayer Pump 9 nozzle (Boom)', 'Sprayer Pump 9 nozzle (Boom)'), ('Sprayer Pump 9 Nozzle (Boom-300 Ltr.)', 'Sprayer Pump 9 Nozzle (Boom-300 Ltr.)'), ('Sub Soiler', 'Sub Soiler'), ('Sugarcane Cage', 'Sugarcane Cage'), ('Tanker (2000 Ltr.)', 'Tanker (2000 Ltr.)'), ('Thresher-2.5 feet', 'Thresher-2.5 feet'), ('Tractor Dozer', 'Tractor Dozer'), ('Tractor Front Mounted Reaper 1.2m', 'Tractor Front Mounted Reaper 1.2m'), ('Tractor Front Mounted Reaper 1.5m', 'Tractor Front Mounted Reaper 1.5m'), ('Tractor Mounted Front end loader', 'Tractor Mounted Front end loader'), ('TRACTOR MOUNTED FRONT END LOADER WITH', 'TRACTOR MOUNTED FRONT END LOADER WITH'), ('Tractor Road Sweeper', 'Tractor Road Sweeper'), ('TRAILER – 60 Feet (7.50 X 16)', 'TRAILER – 60 Feet (7.50 X 16)'), ('Trailer (40 Feet - 6.00x16 tyre)', 'Trailer (40 Feet - 6.00x16 tyre)'), ('Trailer (60 Feet- 6.00x16 tyre)', 'Trailer (60 Feet- 6.00x16 tyre)'), ('Wheel weight - Rear Wheel ( 25 KG)', 'Wheel weight - Rear Wheel ( 25 KG)'), ('Wheel Weight -Front Wheel ( 20 KG )', 'Wheel Weight -Front Wheel ( 20 KG )'), ('Zero Till Seed cum Fertilizer Drill (2 Row)', 'Zero Till Seed cum Fertilizer Drill (2 Row)'), ('Zero Till Seed cum Fertilizer Drill (3 Row)', 'Zero Till Seed cum Fertilizer Drill (3 Row)'), ('Zero Till Seed cum Fertilizer Drill (5 Row)', 'Zero Till Seed cum Fertilizer Drill (5 Row)')], max_length=400, null=True),
        ),
    ]
