# Generated by Django 4.1.7 on 2023-03-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0021_auto_20220919_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_bills',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
